### ISSUE TITLE
Variable naming & metadata

### ISSUE THREAD

**Issue by pbett** [ukcp-data/UKCP18_CVs#2]
I think we can mostly port over the stuff in the [CMIP6 CMOR tables](https://github.com/PCMDI/cmip6-cmor-tables/tree/master/Tables) wholesale and then edit.

The table names aren't really very obvious, so I'd like that to be clearer for a start... 

Looking at them though, I think there's some tweaks we could do
* e.g. do we want repeated definitions in files for different time-frequencies? Isn't the time frequency independent of the variable definition? (cf [monthly data](https://github.com/PCMDI/cmip6-cmor-tables/tree/master/Tables) and [3hly data](https://github.com/PCMDI/cmip6-cmor-tables/blob/master/Tables/CMIP6_3hr.json)
* near-surface air temperatures ("tas") can explicitly say they're at 1.5 m, rather than "(usually, 2 meter)" (cf. [in here](https://github.com/PCMDI/cmip6-cmor-tables/blob/master/Tables/CMIP6_Amon.json)
* I don't think we need "modelling-realm"
* Units: The model outputs temperatures in Kelvin of course, but we'll probably be outputting to the user in °C?
   * (and it really makes me squirm to see things like "kg m-2 s-1" rather than "kg m⁻² s⁻¹", but I guess there's some standard lying behind that?)

**Comment by agstephens** [comment]
These issues are being dealt with in other threads so closing.
