### ISSUE TITLE
Channel Islands - do they need to be in the CVs?

### ISSUE THREAD

**Issue by antony-wilson** [ukcp-data/UKCP18_CVs#20]

**Comment by charliepascoe** [comment]
The Channel Islands are one of the administrative regions listed in UKCP09.  Assuming that UKCP18 uses the same administrative regions then I would say yes, we do need to include the Channel Islands in the CVs.

**Comment by pbett** [comment]
The Channel Islands are in the shapefile of admin regions we're currently using, so we'll need to be able to handle them in a standard way internally even if we choose to not release data for them - so they _do_ need to be in the CVs.

**Comment by antony-wilson** [comment]
The Channel Islands are in the country and admin region CVs so closing this issue
