### ISSUE TITLE
Create a UKCP18 region names CV for each region type

### ISSUE THREAD

**Issue by agstephens** [ukcp-data/UKCP18_CVs#21]
Create a UKCP18 region names CV for each region type - with a lower-case, underscore delimited key and the long names as the values.

**Comment by charliepascoe** [comment]
Note that I have added the lists of UKCP09 "administrative_regions" and "river_basins" to the UKCP18_prob_type.json

**Comment by charliepascoe** [comment]
UKCP09 administrative regions:
"administrative_region":["Channel Islands","East Midlands","East of England","Eastern Scotland","Isle of Man","London","North East England","North West England","Northern Ireland","Northern Scotland","South East England","South West England","Wales","West Midlands","Western Scotland","Yorkshire & Humberside"]

**Comment by charliepascoe** [comment]
UKCP09 river basins:
"river_basin":["Anglian","Argyll","Clyde","Dee","Forth","Humber","Neagh Bann","North East Scotland","North Eastern Ireland","North Highland","North West England","North Western Ireland","Northumbria","Orkney and Shetland","Severn","Solway","South East England","South West England","Tay","Thames","Tweed","West_Highland","Western_Wales"]

**Comment by charliepascoe** [comment]
Listed the UKCP09 river basin and admin regions here because they have been removed from the most recent version of UKCP18_prob_type.json

**Comment by pbett** [comment]
The current shapefiles we're using internally (see ticket 48 on the UKCP18 Climate Services FCM) have the following:

countries:
['Channel Islands', 'England', 'Ireland', 'Isle of Man', 'Northern Ireland', 'Scotland', 'Wales']


admin:
['East Scotland', 'North Scotland', 'West Scotland', 'Northern Ireland', 'East Midlands', 'East of England', 'London', 'North East England', 'North West England', 'South East England', 'South West England', 'Wales', 'West Midlands', 'Yorkshire and Humber', 'Isle of Man', 'Channel Islands']

catchments:
['Tay', 'Orkney and Shetlands', 'Clyde', 'South East England', 'North Eastern Ireland', 'Northumbria', 'Tweed', 'Forth', 'Humber', 'Channel Islands', 'Republic of Ireland', 'Solway', 'North Highland', 'North West England', 'Argyll', 'Thames', 'North Western Ireland', 'Severn', 'Dee', 'West Highland', 'Isle of Man', 'South West England', 'Neagh Bann', 'West Wales', 'North East Scotland', 'Anglian']

Note:
* that the names of the shapefile sets (countries, admin, catchments) are TBD (here), and the basins/catchments shapefile is being revised at the moment.
* the countries list includes Ireland, the Isle of Man and the Channel Islands too

**Comment by antony-wilson** [comment]
I have already manually deleted Ireland from the shape file used by the WPS

**Comment by pbett** [comment]
It's still in ours... It could be problematic that we're using different shapefiles!
They should probably be on GitHub somewhere I suppose?  I'll note this in FCM ticket 48 for NK to look into.

**Comment by antony-wilson** [comment]
I have just been going through other issues and created the admin regions based on NUTS.  I'll revise it to use the names names given above by Phil and changed the abreviations to lowercase unserscore delimited, as requested by Ag

**Comment by antony-wilson** [comment]
created catchment CV file
https://github.com/ukcp-data/UKCP18_CVs/blob/master/UKCP18_catchment.json

**Comment by antony-wilson** [comment]
Just had a chat with Ag
Other CVs are singular, also river basin was preferred and admin is too ambiguous. So we currently have:
- admin_region
- country
- river_basin
