### ISSUE TITLE
Remove scenario info from dataset short_name?

### ISSUE THREAD

**Issue by charliepascoe** [ukcp-data/UKCP18_CVs#26]
LS1 and LS2 both have rcp85 "hard coded" into the  dataset short names but both are expected to have more than one scenario associated with them.

Therefore we will either need to remove the scenario identifier from the dataset short_name or generate additional datasets - one for each scenario.

The solution we choose depends on the granularity we need in our interface to the data.

The UKCP18 Datasets Spreadsheet:
https://docs.google.com/spreadsheets/d/1oNmJAYLGt6UrenY8XH_4gTyZGlFVW9plgyK75L3BN0Y/edit#gid=969822144

UKCP18 Dataset Shortnames:
https://docs.google.com/document/d/1qZLAga8hPU7x36n2s31wR_wjCNzhikO79YZ_KZpr8VQ/edit#

**Comment by agstephens** [comment]
Decision made: we are removing <scenario> from the data set ID - this will reduce the number of MOLES records required and will simplify the generation of example data.
