### ISSUE TITLE
Collection (or Strand) CV - needs clarifying

### ISSUE THREAD

**Issue by agstephens** [ukcp-data/UKCP18_CVs#5]
At the moment we have:

 `UKCP18_collection.json`

It has structure:

```
    "collection":{
        "LS1":"Land Strand 1",
        "LS2":"Land Strand 2",
        "LS3":"Land Strand 3",
        "MS":"Marine Strand",
        "OB":"Observations"
	}
```

Where do we use "LS1" etc? If not at all, then should we use "land-prob", "land-gcm" etc. - which will match the file/directory names.

Should Strand names exist at all in user world? (We think "NO").

**Comment by antony-wilson** [comment]
These are not used by the WPS

**Comment by agstephens** [comment]
Up-to-date so closing.
