### ISSUE TITLE
Country CVs - short versions - where are they used?

### ISSUE THREAD

**Issue by agstephens** [ukcp-data/UKCP18_CVs#6]
In `UKCP18_country.json` - do we need the short names? Lower case?

**Comment by charliepascoe** [comment]
We can expect data by country to be produced by LS2, LS3 and OB5.

Assumption: short names for UKCP18 geographic shapes (country, region, river basin) contain no spaces.
Therefore: short names would make useful as filename attributes.

Capitalisation: we should use consistent case system for all UKCP18 geographic shapes (country, region and river basin).
At the time of writing there are no json vocabularies for regions or river basins with which to compare.

I think Phill Betts is probably best placed to resolve this given his comments on issue #21

**Comment by antony-wilson** [comment]
I have just added an admin region file. This is based on the Nomenclature of Territorial Units for Statistics (NUTS) and uses the NUTS abreviations: UKC, UKD, UKE etc.
The Channel Islands and Isle of Man are not part of NUTS and have the abreviations CI and IOM

**Comment by agstephens** [comment]
Completed.
