### ISSUE TITLE
Fix nominal resolution JSON

### ISSUE THREAD

**Issue by agstephens** [ukcp-data/UKCP18_CVs#9]
`UKCP18_nominal_resolution.json` has keys with underscores - need to converge with file-naming values.

**Comment by antony-wilson** [comment]
Currently the keys are "uk_countries", "admin_regions" and "river_basins". What are the file naming values?

**Comment by agstephens** [comment]
We need to decide on these.

**Comment by agstephens** [comment]
Not needed.
